application: arsenaljpfans
version: 4
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /
  script: followresult.py

- url: /ArsenalTVGetter
  script: ArsenalTVGetter.py
  login: admin
